# Generated by Django 4.1.2 on 2022-10-23 14:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('part_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ComponentAbstract',
                'verbose_name_plural': 'ComponentsAbstract',
                'ordering': ('part_number',),
            },
        ),
        migrations.CreateModel(
            name='ComponentInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('date_received', models.DateField()),
                ('received_from', models.CharField(max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.component')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'ordering': ('component',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='RepairCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'MRO',
                'verbose_name_plural': "MRO's",
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Condition/Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ('condition',),
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
            },
        ),
        migrations.CreateModel(
            name='Shelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.case')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.warehouse')),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
                'ordering': ('order_number',),
            },
        ),
        migrations.CreateModel(
            name='RepairManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shipped', models.DateField()),
                ('date_received', models.DateField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.componentinstance')),
                ('condition_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.status')),
                ('repair_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.repaircompany')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.storestaff')),
            ],
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='staff_received',
            field=models.ManyToManyField(related_name='staff_received', to='StoreManagement.storestaff'),
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='status',
            field=models.ManyToManyField(to='StoreManagement.status'),
        ),
        migrations.CreateModel(
            name='ComponentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shipped', models.DateField()),
                ('shipped_to', models.CharField(max_length=30)),
                ('invoice', models.CharField(max_length=30)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.componentinstance')),
                ('shipped_status', models.ManyToManyField(to='StoreManagement.status')),
                ('staff_shipped', models.ManyToManyField(related_name='staff_shipped', to='StoreManagement.storestaff')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.customer'),
        ),
        migrations.AddField(
            model_name='case',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.warehouse'),
        ),
    ]
