# Generated by Django 4.1.2 on 2022-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate'),
        ),
    ]
