# Generated by Django 4.1.2 on 2022-11-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagement', '0002_componentinstance_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
