# Generated by Django 4.1.2 on 2022-11-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagement', '0004_alter_componentinstance_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/certificate/'),
        ),
    ]
