# Generated by Django 4.1.2 on 2022-11-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagement', '0010_alter_componentinstance_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'ComponentDescription&PN', 'verbose_name_plural': 'ComponentDescription&PN'},
        ),
        migrations.RemoveField(
            model_name='componentinstance',
            name='location',
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.warehouse'),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='componentinstance',
            name='us_part_condition',
            field=models.CharField(blank=True, default='Repairable', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Shelve',
        ),
        migrations.AddField(
            model_name='componentinstance',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StoreManagement.shelf'),
        ),
    ]
