# Generated by Django 4.1.2 on 2022-11-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreManagement', '0013_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
